---
- name: activity4
  become: yes
  hosts: webserver
  tasks:
    - name: fail back msg if the os is not in our palybook
      ansible.builtin.fail:
        msg: fail the playbook if the os is not ubuntu and "RedHat"
      when: ansible_facts['os_family'] != "Debian" and ansible_facts['os_family'] != "RedHat"  
    - name: install apache and php
      ansible.builtin.package:
        name: "{{ all_packages  }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: install apache and php
      ansible.builtin.package:
        name: "{{ all_packages }}"
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "RedHat"
    - name: copy php file into server2
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: enable service 
      ansible.builtin.service:
        name: "{{ package_name }}"
        enabled: yes
        state: started
      when: ansible_facts['os_family'] == "RedHat"
