---
- name: install tomcat
  become: yes
  hosts: all
  vars: 
    java_version: "11"
    homedir: /opt/tomcat
    VERSION: "10.1.14"
  tasks:
    - name: install java 11
      ansible.builtin.apt:
        name: "openjdk-{{ java_version }}-jdk"
        state: present
        update_cache: yes
    - name: create tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present 
    - name: add tomcat user 
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        shell: /bin/false
    - name: download tomcat 
      ansible.builtin.get_url:
        url: "https://www-eu.apache.org/dist/tomcat/tomcat-10/v{{VERSION}}/bin/apache-tomcat-{{VERSION}}.tar.gz"
        dest: "/tmp/apache-tomcat-{{VERSION}}.tar.gz"
    - name: ceate directory
      ansible.builtin.file:
        path: "{{ homedir }}"
        state: directory
    - name: extract files into remote hosts
      ansible.builtin.unarchive:
        src: "/tmp/apache-tomcat-{{VERSION}}.tar.gz"
        dest: "{{ homedir }}"
        remote_src: yes
    - name: create symbolic link
      ansible.builtin.file:
        src: "{{ homedir }}"
        dest: /opt/tomcat/latest
        state: link
    - name: give ownership to the files
      ansible.builtin.file:
        path: "{{ homedir }}"
        owner: tomcat
        group: tomcat
        state: directory

    - name: Check if Tomcat bin directory exists
      stat:
        path: /opt/tomcat/latest/bin
      register: tomcat_bin_dir

    - name: Check if .sh files exist in the Tomcat bin directory
      find:
        paths: /opt/tomcat/latest/bin
        patterns: "*.sh"
      register: sh_file    
      
    - name: make .sh files executable
      ansible.builtin.command: sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    
    - name: template for service file
      ansible.builtin.template:
        src: template/service.j2
        dest  : /etc/systemd/system/tomcat.service
    - name: deamon reload
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: start service tomcat
      ansible.builtin.service:
        name: tomcat
        state: started
        enabled: yes
      ignore_errors: yes
    - name: Gather Tomcat service status
      command: systemctl status tomcat.service
      register: tomcat_status
      ignore_errors: yes

    - name: Gather Tomcat service journal logs
      command: journalctl -xeu tomcat.service
      register: tomcat_journal
      ignore_errors: yes

    - name: check the status
      ansible.builtin.command: systemctl status tomcat
      register: myoutput

    - name: debug
      ansible.builtin.debug:
        var: myoutput.stdout_lines
      
        
    
    

              
      
      