---
- name: install tomcat
  become: yes
  hosts: all
  vars: 
    java_version: "11"
    homedir: /opt/tomcat
    VERSION: "10.1.14"
  tasks:
    - name: install java 11
      ansible.builtin.apt:
        name: "openjdk-{{ java_version }}-jdk"
        state: present
        update_cache: yes
    - name: create tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present 
    - name: add tomcat user 
      ansible.builtin.user:
        name: tomcat
        group: tomcat
        shell: /bin/false
    - name: download tomcat 
      ansible.builtin.get_url:
        url: "https://www-eu.apache.org/dist/tomcat/tomcat-10/v${VERSION}/bin/apache-tomcat-${VERSION}.tar.gz"
        dest: "/tmp/apache-tomcat-${{VERSION}}.tar.gz"
    - name: ceate directory
      ansible.builtin.file:
        path: tomcat
        state: directory
    - name: extract files into remote hosts
      ansible.builtin.unarchive:
        src: "/tmp"
        dest: "{{ homedir }}"

              
      
      