---
- name: install tomcat
  become: yes
  hosts: all
  vars: 
    java-version: "11"
    homedir: /opt/tomcat
    MAJOR_VERSION: "10"
    VERSION: "10.1.14"
  tasks:
    - name: install java 11
      ansible.builtin.apt:
        name: opnejdk-{{" java-version "}}-jdk
        state: present
        update_cache: yes
    - name: create tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present 
    - name: add tomcat user with group tomcat
      ansible.builtin.user:
      name: tomcat
      group: tomcat
      shell: /bin/false
    - name: download tomcat 
      ansible.builtin.get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-${{MAJOR_VERSION}}/v${{VERSION}}/bin/apache-tomcat-${{VERSION}}.tar.gz"
        dest: "/tmp"
    - name: ceate directory
      ansible.builtin.file:
        path: tomcat
        state: directory
    - name: extract files into remote hosts
      ansible.builtin.unarchive:
        src: "/tmp"
        dest: "{{ homedir }}"

              
      
      